---
- name: installing flatpaks
  flatpak:
    name:
      - com.belmoussaoui.Authenticator
      - xyz.armcord.ArmCord
      - com.github.tchx84.Flatseal
      - com.makemkv.MakeMKV
      - com.teamspeak.TeamSpeak
      - io.github.celluloid_player.Celluloid
      - org.gimp.GIMP
      - org.gnome.World.PikaBackup
      - org.inkscape.Inkscape
      - org.remmina.Remmina
      - org.telegram.desktop
      - com.valvesoftware.Steam
      - org.gnome.World.Secrets
    state: present
